---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp
  namespace: demo
  labels:
    team: webapp
spec:
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app: webapp
