---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: http
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      metric:
        # use the metric that you used above: pods/http_requests
        name: http_requests_per_second
      target:
        # target 50 milli-requests per second,
        type: AverageValue
        averageValue: 50m
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 80
